### ISSUE TITLE
Infografia de Hilos en c#

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/infografia-de-hilos-MLR062998#2]
[hilos_infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-MLR062998/files/6490968/hilos_infografia.pdf)

**Comment by Azucena-Tejeda** [comment]
calificación 19

**Comment by josealfredo79** [comment]
esta bien hecho y revisado.
